### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Feeclichette** [haimbar/RCMap#2]
Hi, I'm working with RCMap, and when I chose my data folder in the main menu, the following error message appeared :

RCMap command-line interface.
Opening project folder:C:\Nouveau dossier\Data\...

Erreur dans `[.data.frame`(piledat, , 3:ncol(piledat)) : 
  colonnes non définies sélectionnées

I didnt find any mistake in my folders or columns names and I'm not sure to understand the type of error indicated.

Thanks in advance for help.

**Comment by haimbar** [comment]
Hi,
Thanks for providing the data files!
There are a couple of issues which cause the errors. 
First, the delimiter has to be a comma, not a semicolon (in all 4 files). Notice that one of the labels (from sorter 16) contained a comma(Activité, sport et physique), so before replacing all the semicolons with commas, the comma in the label given by sorter 16 has to be replaced by something other than ; and ,.
Second, there are only 60 statements in the Statement, but sorter 20 put statement 66 in one pile, and sorter 15 put statement 74 in a pile. These two invalid statement numbers have to be fixed in order for the adjacency matrix to be constructed.

**Comment by Feeclichette** [comment]
Thank you very much for your detailed answer and for taking the time to check my data files.
I'm working on fixing the issues you mentioned, hope everything works well with these changes! Many thanks again for your time, it is greatly appreciated!

**Comment by haimbar** [comment]
Great!
Let me know how it goes.
